@startuml Classes
left to right direction

class Afficher{
    + void MenuOuverture()
    + void SelectionCarte()
    + void Carte(Card Carte)
    + void Gagnant(Player joueur)

}

class Game{
    - Player p1
    - Player p2

    + Game(Player p1, Player p2)
    + void BouclePrincipale()
    + void isWinning(Player p)
    + roundWin(Card P1Card, Card P2Card)
}

class Card{
    - int _power
    - int _color
    - int _type

    + Card generateRandomCard()
    + int getPower()
    + void setPower(int p)
    + int getColor()
    + void setColor(int c)
    + int getType()
    + void setType(int t)
}

class Player{
    - vecteur<Carte*> _deck
    - vecteur<Carte*> _wins

    + bool isWinning()
}

Player --> Card
Game --> Player

Game -- Afficher
Card -- Afficher
Player -- Afficher

@enduml