@startuml Classes
left to right direction

class main{
    + int main(argc:int, argv[]:char*)
}

class menuWindow{
    - timer : QTimer*
	- label_Title : QLabel*
	- label_info, label_PlayerName : QLabel* 
	- button_P1, button_P2, button_Info: QPushButton*
	- c1, c1P, c1E : QLabel* 

	- solo : bool
	- game : Game*
	- winner, wp, activeP, lastActiveP, iCard, iCardP1, iCardP2 : int
	- p1Name, p2Name : std::string
	- selectedStyle : const char*

    + menuWindow(parent : QWidget*);
	+ ~menuWindow();

	+ initButtons()
	+ initImg()
	+ initAction()
	+ initLabel()
	+ initLineEdit()

	+ showP1_Options()
	+ showP2_Options()
	+ show_Info()
	+ show_Menu()

	+ newGame(solo : bool)
	+ gameLoop()
	+ createCards()
	+ showPlayerCard(i : int)
	+ changeSelected(last : int, newI : int)
}

class QWidget{
}
class QLabel{
}
class QPushButton{
}
class QTimer{
}
class QLineEdit{
}

main --o menuWindow
menuWindow *-- QTimer
menuWindow *-- QPushButton
menuWindow *-- QLineEdit
menuWindow *-- QLabel
menuWindow --|> QWidget

@enduml